spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hci
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher